# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 21:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateTimeField(verbose_name='date added')),
                ('lot_number', models.CharField(max_length=200)),
                ('quantity', models.IntegerField(default=0)),
                ('location', models.CharField(max_length=100)),
                ('pieces', models.IntegerField(default=0)),
                ('notes', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('sm_lot_number', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='inventory',
            name='product_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.Product'),
        ),
    ]
