# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 21:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='product_name',
            new_name='product',
        ),
    ]
