# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-13 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_auto_20160606_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='popular',
            field=models.CharField(default=0, max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inventory',
            name='dessicate',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='standard',
            field=models.CharField(max_length=3),
        ),
    ]
