# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-13 20:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_auto_20160613_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='dessicate',
            field=models.CharField(default='No', max_length=3),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='standard',
            field=models.CharField(default='Yes', max_length=3),
        ),
        migrations.AlterField(
            model_name='product',
            name='popular',
            field=models.CharField(default='No', max_length=3),
        ),
    ]
