# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-21 20:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_auto_20160613_1533'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='date')),
                ('quantity', models.IntegerField(default=0)),
                ('client', models.CharField(max_length=100)),
                ('notes', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('DEX', 'Pressed Dextrose'), ('GUM', 'Bubble Gum'), ('PSG', 'Panned Sugar'), ('JAW', 'Jawbreaker')], default='DEX', max_length=3),
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.Product'),
        ),
    ]
