# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-23 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_auto_20160621_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('0', 'Pending'), ('1', 'Approved')], default='0', max_length=1),
        ),
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.FileField(default='', upload_to=b''),
        ),
    ]
