# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-23 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_auto_20160623_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('dex', 'Pressed Dextrose'), ('gum', 'Bubble Gum'), ('psg', 'Panned Sugar'), ('jaw', 'Jawbreaker')], default='dex', max_length=3),
        ),
    ]
