# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-23 21:06
from __future__ import unicode_literals

from django.db import migrations, models
import tracker.models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_auto_20160623_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to=tracker.models.get_image_path),
        ),
    ]
