# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-05 21:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_auto_20160623_1606'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pending_Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.IntegerField(default=1)),
                ('quantity', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='order',
            name='stock',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='label',
            field=models.CharField(choices=[('0', 'No Label'), ('1', 'Has labels'), ('2', 'Partially labelled')], default='0', max_length=1),
        ),
        migrations.AddField(
            model_name='pending_stock',
            name='inventory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.Inventory'),
        ),
    ]
