# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-04 21:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_auto_20160705_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='pending_stock',
            name='status',
            field=models.CharField(default='Pending', max_length=10),
        ),
    ]
