# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-17 19:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0011_pending_stock_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='alerts',
            field=models.IntegerField(default=0),
        ),
    ]
