# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-08 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0013_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Labels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='None', max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='inventory',
            name='label',
            field=models.CharField(default='None', max_length=30),
        ),
    ]
