# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-08 22:14
from __future__ import unicode_literals

from django.db import migrations, models
import tracker.models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0015_auto_20161108_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to=tracker.models.get_image_path),
        ),
    ]
